-- GENERATED by scripts/add-v997-colourways-2026-09.mjs, then extended by hand
-- for C836G (see the foot of the file). Regenerate the V997 half with:
--   node scripts/add-v997-colourways-2026-09.mjs
--
-- The filename is load-bearing, the same way product-outline-dimensions-* is.
-- db-build.mjs loads non-ORDER files alphabetically and this one reuses image
-- ids 9023, 9050 and 9051 from product-images-2026-08.sql, so it has to sort
-- after it: "product-s" > "product-i". Called product-colourways-* it loads
-- first and fails on a foreign key.
--
-- V997's AG Grey and Pearl White colourways, from the 2026-08 shoot folder that
-- the first import only took Black from. The 2026 catalogue p.08 sells all three.
--
-- These are swatches on the existing page, not sibling products: V917 and DWID3
-- use variant_group because they have to, and copying that here would put three
-- near-identical pages on three URLs and split the traffic /vatti-range-hood-v997/
-- already earns. See product_colourway in schema.sql.

INSERT INTO image (id, url, legacy_url, alt, width, height) VALUES (9095, 'https://cdn.vattimalaysia.com/2026/09/vatti-range-hood-v997-ag-grey-front.webp', NULL, 'Range Hood V997 in AG Grey, front view', 1057, 995);
INSERT INTO image (id, url, legacy_url, alt, width, height) VALUES (9096, 'https://cdn.vattimalaysia.com/2026/09/vatti-range-hood-v997-ag-grey-quarter-front.webp', NULL, 'Range Hood V997 in AG Grey, angled view', 803, 1016);
INSERT INTO image (id, url, legacy_url, alt, width, height) VALUES (9097, 'https://cdn.vattimalaysia.com/2026/09/vatti-range-hood-v997-ag-grey-side.webp', NULL, 'Range Hood V997 in AG Grey, side view', 446, 988);
INSERT INTO image (id, url, legacy_url, alt, width, height) VALUES (9098, 'https://cdn.vattimalaysia.com/2026/09/vatti-range-hood-v997-pearl-white-front.webp', NULL, 'Range Hood V997 in Pearl White, front view', 1045, 1006);
INSERT INTO image (id, url, legacy_url, alt, width, height) VALUES (9099, 'https://cdn.vattimalaysia.com/2026/09/vatti-range-hood-v997-pearl-white-quarter-front.webp', NULL, 'Range Hood V997 in Pearl White, angled view', 871, 1008);
INSERT INTO image (id, url, legacy_url, alt, width, height) VALUES (9100, 'https://cdn.vattimalaysia.com/2026/09/vatti-range-hood-v997-pearl-white-side.webp', NULL, 'Range Hood V997 in Pearl White, side view', 451, 1001);

INSERT INTO product_image (product_id, image_id, position, role) VALUES (11, 9095, 915, 'gallery');
INSERT INTO product_image (product_id, image_id, position, role) VALUES (11, 9096, 916, 'gallery');
INSERT INTO product_image (product_id, image_id, position, role) VALUES (11, 9097, 917, 'gallery');
INSERT INTO product_image (product_id, image_id, position, role) VALUES (11, 9098, 918, 'gallery');
INSERT INTO product_image (product_id, image_id, position, role) VALUES (11, 9099, 919, 'gallery');
INSERT INTO product_image (product_id, image_id, position, role) VALUES (11, 9100, 920, 'gallery');

-- Dark Black is the colourway the page already showed. Its front shot is image
-- 9023, uploaded in the 2026-08 batch and still the product hero, so it is
-- reused rather than re-uploaded under a second key. Its three shots were named
-- before there was a second finish to tell them apart from, so they say which
-- one they are now that the gallery holds all three.
UPDATE image SET alt = 'Range Hood V997 in Dark Black, front view'   WHERE id = 9023;
UPDATE image SET alt = 'Range Hood V997 in Dark Black, angled view'  WHERE id = 9024;
UPDATE image SET alt = 'Range Hood V997 in Dark Black, side view'    WHERE id = 9025;

INSERT INTO product_colourway (product_id, position, name, image_id) VALUES (11, 1, 'Dark Black', 9023);
INSERT INTO product_colourway (product_id, position, name, image_id) VALUES (11, 2, 'AG Grey', 9095);
INSERT INTO product_colourway (product_id, position, name, image_id) VALUES (11, 3, 'Pearl White', 9098);

-- ── C836G ───────────────────────────────────────────────────────────────────
-- Catalogue p.11 sells the C836G in AG Grey and Black. Both shots were already
-- uploaded in 2026-08: the folder is named "C836 (AG Grey)" but its F.png is the
-- BLACK hob, and the AG Grey one is the separately named file, which landed as a
-- "detail view" gallery image. Nothing new to upload, only the labels are wrong.
UPDATE image SET alt = 'VATTI Flexi Hob C836G in Black, front view' WHERE id = 9050;
UPDATE image SET alt = 'VATTI Flexi Hob C836G in AG Grey, front view' WHERE id = 9051;

INSERT INTO product_colourway (product_id, position, name, image_id)
SELECT id, 1, 'Black', 9050 FROM product WHERE slug = 'vatti-flexi-hob-c836g';
INSERT INTO product_colourway (product_id, position, name, image_id)
SELECT id, 2, 'AG Grey', 9051 FROM product WHERE slug = 'vatti-flexi-hob-c836g';
