-- Generated by scripts/import-redirects.mjs from research/url-inventory.json.
-- Do not edit by hand: re-run the importer.
--
-- Every legacy URL resolves 200 or 301, never 404 (CLAUDE.md § The one rule).
-- /wp-content/uploads/** is NOT in here: next.config.ts 301s that whole prefix to
-- the R2 CDN before routing, so a row here would never fire.
--
-- 177 redirects, from an inventory of 483 URLs probed on 2026-08-08.

DELETE FROM redirect;

-- ────────────────────────────────────────────────────────────────────────────
-- Owner-confirmed, and slug typos with one obvious target (9)
-- ────────────────────────────────────────────────────────────────────────────
-- empty orphan stub; owner-confirmed
INSERT INTO redirect (from_path, to_path, code) VALUES ('/oven/', '/combi-and-steam-oven-in-malaysia/', 301);
-- deleted post, 404 today; nearest live page by topic — the one inferred target here
INSERT INTO redirect (from_path, to_path, code) VALUES ('/best-kitchen-hoods-for-modern-malaysian-cooking/', '/kitchen-hood-in-malaysia/', 301);
-- 404 today; slug is the live post's minus one word
INSERT INTO redirect (from_path, to_path, code) VALUES ('/buying-guide/is-an-infrared-stove-worth-it/', '/buying-guide/is-an-infrared-gas-stove-worth-it/', 301);
-- 404 today; slug is the live post's minus one word
INSERT INTO redirect (from_path, to_path, code) VALUES ('/buying-guide/is-infrared-gas-stove-worth-it/', '/buying-guide/is-an-infrared-gas-stove-worth-it/', 301);
-- 404 today; /contact-us/ is the live contact page
INSERT INTO redirect (from_path, to_path, code) VALUES ('/contact/', '/contact-us/', 301);
-- 404 today; slug is the live post's minus one word
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-unstick-aluminum-foil-handy-tips/', '/tips-tricks/how-to-unstick-food-from-aluminum-foil-handy-tips/', 301);
-- empty orphan stub; owner-confirmed
INSERT INTO redirect (from_path, to_path, code) VALUES ('/oven/recipe/', '/category/recipe/', 301);
-- true duplicate; owner-confirmed
INSERT INTO redirect (from_path, to_path, code) VALUES ('/tips-tricks/clean-baking-sheets-2/', '/tips-tricks/clean-baking-sheets/', 301);
-- letter O -> the live slug's digit zero; 404 today
INSERT INTO redirect (from_path, to_path, code) VALUES ('/vatti-built-in-air-fryer-oven-o7559/', '/vatti-built-in-air-fryer-oven-07559/', 301);

-- ────────────────────────────────────────────────────────────────────────────
-- Duplicate URL families — the member the live site dropped, pointed at the one it kept (38)
-- ────────────────────────────────────────────────────────────────────────────
-- /tips-tricks/how-to-clean-white-spots-on-glass-stove-tops/ is the only member the live site still serves (/how-to-clean-white-spots-on-glass-stove-tops/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-clean-white-spots-on-glass-stove-tops/', '/tips-tricks/how-to-clean-white-spots-on-glass-stove-tops/', 301);
-- /buying-guide/is-infrared-gas-stove-good/ is the only member the live site still serves (/is-infrared-gas-stove-good/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/is-infrared-gas-stove-good/', '/buying-guide/is-infrared-gas-stove-good/', 301);
-- /tips-tricks/how-to-remove-cloudiness-from-glass-stovetop/ is the only member the live site still serves (/how-to-remove-cloudiness-from-glass-stovetop/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-remove-cloudiness-from-glass-stovetop/', '/tips-tricks/how-to-remove-cloudiness-from-glass-stovetop/', 301);
-- /tips-tricks/how-to-unstick-food-from-aluminum-foil-handy-tips/ is the only member the live site still serves (/how-to-unstick-food-from-aluminum-foil-handy-tips/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-unstick-food-from-aluminum-foil-handy-tips/', '/tips-tricks/how-to-unstick-food-from-aluminum-foil-handy-tips/', 301);
-- /buying-guide/is-an-infrared-gas-stove-worth-it/ is the only member the live site still serves (/is-an-infrared-gas-stove-worth-it/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/is-an-infrared-gas-stove-worth-it/', '/buying-guide/is-an-infrared-gas-stove-worth-it/', 301);
-- /tips-tricks/dishwasher-salt-alternative/ is the only member the live site still serves (/dishwasher-salt-alternative/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/dishwasher-salt-alternative/', '/tips-tricks/dishwasher-salt-alternative/', 301);
-- /buying-guide/convection-oven-vs-infrared-which-should-you-choose/ is the only member the live site still serves (/convection-oven-vs-infrared-which-should-you-choose/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/convection-oven-vs-infrared-which-should-you-choose/', '/buying-guide/convection-oven-vs-infrared-which-should-you-choose/', 301);
-- /tips-tricks/how-to-remove-onion-smell-from-wood-cutting-boards/ is the only member the live site still serves (/how-to-remove-onion-smell-from-wood-cutting-boards/ is 301)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-remove-onion-smell-from-wood-cutting-boards/', '/tips-tricks/how-to-remove-onion-smell-from-wood-cutting-boards/', 301);
-- /buying-guide/is-a-ceramic-cooktop-same-as-a-glass-cooktop/ is the only member the live site still serves (/is-a-ceramic-cooktop-same-as-a-glass-cooktop/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/is-a-ceramic-cooktop-same-as-a-glass-cooktop/', '/buying-guide/is-a-ceramic-cooktop-same-as-a-glass-cooktop/', 301);
-- /buying-guide/ceramic-cooker-vs-infrared-cooker-what-is-the-difference/ is the only member the live site still serves (/ceramic-cooker-vs-infrared-cooker-what-is-the-difference/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/ceramic-cooker-vs-infrared-cooker-what-is-the-difference/', '/buying-guide/ceramic-cooker-vs-infrared-cooker-what-is-the-difference/', 301);
-- /buying-guide/difference-between-induction-and-electric-cooker/ is the only member the live site still serves (/difference-between-induction-and-electric-cooker/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/difference-between-induction-and-electric-cooker/', '/buying-guide/difference-between-induction-and-electric-cooker/', 301);
-- /buying-guide/which-is-better-induction-or-ceramic-cooker/ is the only member the live site still serves (/which-is-better-induction-or-ceramic-cooker/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/which-is-better-induction-or-ceramic-cooker/', '/buying-guide/which-is-better-induction-or-ceramic-cooker/', 301);
-- /recipe/5-best-asian-soup-recipes/ is the only member the live site still serves (/5-best-asian-soup-recipes/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/5-best-asian-soup-recipes/', '/recipe/5-best-asian-soup-recipes/', 301);
-- /recipe/spicy-enoki-mushrooms-recipe-step-by-step-guide/ is the only member the live site still serves (/spicy-enoki-mushrooms-recipe-step-by-step-guide/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/spicy-enoki-mushrooms-recipe-step-by-step-guide/', '/recipe/spicy-enoki-mushrooms-recipe-step-by-step-guide/', 301);
-- /recipe/acai-bowl-recipes-quick-and-easy/ is the only member the live site still serves (/acai-bowl-recipes-quick-and-easy/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/acai-bowl-recipes-quick-and-easy/', '/recipe/acai-bowl-recipes-quick-and-easy/', 301);
-- /recipe/chickpea-and-spinach-breakfast-burrito-recipes/ is the only member the live site still serves (/chickpea-and-spinach-breakfast-burrito-recipes/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/chickpea-and-spinach-breakfast-burrito-recipes/', '/recipe/chickpea-and-spinach-breakfast-burrito-recipes/', 301);
-- /recipe/scallion-pancake-recipe/ is the only member the live site still serves (/scallion-pancake-recipe/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/scallion-pancake-recipe/', '/recipe/scallion-pancake-recipe/', 301);
-- /recipe/keto-chicken-recipes-for-weight-loss/ is the only member the live site still serves (/keto-chicken-recipes-for-weight-loss/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/keto-chicken-recipes-for-weight-loss/', '/recipe/keto-chicken-recipes-for-weight-loss/', 301);
-- /recipe/5-delicous-and-easy-rice-cooker-recipes-for-every-meal/ is the only member the live site still serves (/5-delicous-and-easy-rice-cooker-recipes-for-every-meal/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/5-delicous-and-easy-rice-cooker-recipes-for-every-meal/', '/recipe/5-delicous-and-easy-rice-cooker-recipes-for-every-meal/', 301);
-- /recipe/blueberry-smoothie-bowl-with-almond-butter-recipes/ is the only member the live site still serves (/blueberry-smoothie-bowl-with-almond-butter-recipes/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/blueberry-smoothie-bowl-with-almond-butter-recipes/', '/recipe/blueberry-smoothie-bowl-with-almond-butter-recipes/', 301);
-- /tips-tricks/gas-hob-igniter-not-working/ is the only member the live site still serves (/gas-hob-igniter-not-working/ is 301)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/gas-hob-igniter-not-working/', '/tips-tricks/gas-hob-igniter-not-working/', 301);
-- /tips-tricks/how-to-place-a-dishwasher-in-the-kitchen/ is the only member the live site still serves (/how-to-place-a-dishwasher-in-the-kitchen/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-place-a-dishwasher-in-the-kitchen/', '/tips-tricks/how-to-place-a-dishwasher-in-the-kitchen/', 301);
-- /tips-tricks/how-to-use-charcoal-at-home/ is the only member the live site still serves (/how-to-use-charcoal-at-home/ is 301)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-use-charcoal-at-home/', '/tips-tricks/how-to-use-charcoal-at-home/', 301);
-- /recipe/5-easy-homemade-pasta-sauce-recipes/ is the only member the live site still serves (/5-easy-homemade-pasta-sauce-recipes/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/5-easy-homemade-pasta-sauce-recipes/', '/recipe/5-easy-homemade-pasta-sauce-recipes/', 301);
-- /recipe/5-quick-and-easy-one-pot-rice-meals-for-family-gatherings/ is the only member the live site still serves (/5-quick-and-easy-one-pot-rice-meals-for-family-gatherings/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/5-quick-and-easy-one-pot-rice-meals-for-family-gatherings/', '/recipe/5-quick-and-easy-one-pot-rice-meals-for-family-gatherings/', 301);
-- /recipe/5-quick-smoothie-bowl-recipes/ is the only member the live site still serves (/5-quick-smoothie-bowl-recipes/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/5-quick-smoothie-bowl-recipes/', '/recipe/5-quick-smoothie-bowl-recipes/', 301);
-- /recipe/baked-sweet-potato-recipes/ is the only member the live site still serves (/baked-sweet-potato-recipes/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/baked-sweet-potato-recipes/', '/recipe/baked-sweet-potato-recipes/', 301);
-- /buying-guide/convection-oven-or-regular-oven/ is the only member the live site still serves (/convection-oven-or-regular-oven/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/convection-oven-or-regular-oven/', '/buying-guide/convection-oven-or-regular-oven/', 301);
-- /tips-tricks/how-to-clean-a-burnt-microwave-oven/ is the only member the live site still serves (/how-to-clean-a-burnt-microwave-oven/ is 301)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-clean-a-burnt-microwave-oven/', '/tips-tricks/how-to-clean-a-burnt-microwave-oven/', 301);
-- /tips-tricks/how-to-clean-oven-racks-tips-and-tricks/ is the only member the live site still serves (/how-to-clean-oven-racks-tips-and-tricks/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-clean-oven-racks-tips-and-tricks/', '/tips-tricks/how-to-clean-oven-racks-tips-and-tricks/', 301);
-- /tips-tricks/how-to-clean-stove-grates-a-step-by-step-guide/ is the only member the live site still serves (/how-to-clean-stove-grates-a-step-by-step-guide/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-clean-stove-grates-a-step-by-step-guide/', '/tips-tricks/how-to-clean-stove-grates-a-step-by-step-guide/', 301);
-- /buying-guide/is-a-dishwasher-worth-it/ is the only member the live site still serves (/is-a-dishwasher-worth-it/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/is-a-dishwasher-worth-it/', '/buying-guide/is-a-dishwasher-worth-it/', 301);
-- /tips-tricks/kitchen-hygiene-and-cooking-safety-10-tips/ is the only member the live site still serves (/kitchen-hygiene-and-cooking-safety-10-tips/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hygiene-and-cooking-safety-10-tips/', '/tips-tricks/kitchen-hygiene-and-cooking-safety-10-tips/', 301);
-- /recipe/oven-roasted-potatoes/ is the only member the live site still serves (/oven-roasted-potatoes/ is 301)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/oven-roasted-potatoes/', '/recipe/oven-roasted-potatoes/', 301);
-- /recipe/peanut-butter-and-banana-overnight-oats-recipes/ is the only member the live site still serves (/peanut-butter-and-banana-overnight-oats-recipes/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/peanut-butter-and-banana-overnight-oats-recipes/', '/recipe/peanut-butter-and-banana-overnight-oats-recipes/', 301);
-- /tips-tricks/stainless-steel-cleaning-solutions-5-tips/ is the only member the live site still serves (/stainless-steel-cleaning-solutions-5-tips/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/stainless-steel-cleaning-solutions-5-tips/', '/tips-tricks/stainless-steel-cleaning-solutions-5-tips/', 301);
-- /recipe/sweet-potato-breakfast-hash-with-black-bean-recipes/ is the only member the live site still serves (/sweet-potato-breakfast-hash-with-black-bean-recipes/ is 404)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/sweet-potato-breakfast-hash-with-black-bean-recipes/', '/recipe/sweet-potato-breakfast-hash-with-black-bean-recipes/', 301);
-- /tips-tricks/what-can-you-wash-in-dishwasher/ is the only member the live site still serves (/what-can-you-wash-in-dishwasher/ is 301)
INSERT INTO redirect (from_path, to_path, code) VALUES ('/what-can-you-wash-in-dishwasher/', '/tips-tricks/what-can-you-wash-in-dishwasher/', 301);

-- ────────────────────────────────────────────────────────────────────────────
-- Live 301s on vattimalaysia.com today, reproduced as-is (98)
-- ────────────────────────────────────────────────────────────────────────────
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood/', '/kitchen-hood-in-malaysia/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/steamer-combi-oven/', '/combi-and-steam-oven-in-malaysia/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cooker-hob/', '/cooker-hob-in-malaysia/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/dishwasher/', '/dishwasher-in-malaysia/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/one-tap-purifier/', '/one-tap-purifier-in-malaysia/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/built-in-oven/', '/combi-and-steam-oven-in-malaysia/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/types-of-range-hoods/', '/buying-guide/types-of-range-hoods/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-remove-scratches-on-stove-top/', '/tips-tricks/how-to-remove-scratches-on-stove-top/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/vatti-oylimpic-hob-m821g/', '/vatti-oylimpic-hob-m822g/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/wall-oven-sizes-how-to-choose-perfect-built-in-oven-size/', '/buying-guide/wall-oven-sizes-how-to-choose-perfect-built-in-oven-size/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cream-puff-with-custard-filing-recipe/', '/recipe/cream-puff-with-custard-filing-recipe/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/glass-vs-stainless-gas-hob-which-gas-hob-are-best/', '/buying-guide/glass-vs-stainless-gas-hob-which-gas-hob-are-best/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/home-2/', '/vatti-dishwasher-dwbb7/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/buying-guide/induction-cooker-vs-gas-stove-in-malaysia-what-is-the-difference/', '/buying-guide/induction-cooker-vs-gas-stove/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/what-is-a-combi-oven/', '/buying-guide/what-is-a-combi-oven/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-remove-scratches-on-stove-top-comprehensive-method/', '/tips-tricks/how-to-remove-scratches-on-stove-top/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/simple-chicken-lasagna-recipe/', '/recipe/simple-chicken-lasagna-recipe/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/weight-loss-smoothie/', '/recipe/detox-smoothie-recipe-for-weight-loss/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/adamas/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/alat-dapur-shah-alam/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/alatdapur-cheras/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/alatdapur-semenyih/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/ban-hin-bee-sdn-bhd-kitchentech/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/benova-marketing/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/bright-scott-electrical-sdn-bhd-sandakan/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/darxon_sr/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/de-bathlabz-batu-tiga-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/de-bathlabz-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/detox-smoothie-recipe-for-weight-loss/', '/recipe/detox-smoothie-recipe-for-weight-loss/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/easton_ec/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/eastone-gallery-sdn-bhd_tunjung/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/elementor-hf/elementor-5036/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/emart-plentong_sr/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/emartnusa_sr/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/esh_kv/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/esh-electrical-ekocheras/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/esh-electrical-kepong/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/esh-electrical-the-starling/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/eurotan_kv/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/eurotan-enterprise-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/felicita-home-deco-johor-bahru/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/filken-bukit-indah/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/filken-kulai/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/flo-plus-home-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/grand-filken-setia-indah/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/heng-foong_nr/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/home-care_sr/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/home-style-marketing-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/homemade-granola-recipe-2024/', '/recipe/how-to-prepare-granola/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/homeworks_sounthern/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/homeworks-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/how-to-prepare-granola/', '/recipe/how-to-prepare-granola/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/in-ceramics-sdn-bhd/', '/', 301);
-- live 301 lands on a 404 (/which-is-better-induction-or-ceramic-cooker/); repointed at the live article
INSERT INTO redirect (from_path, to_path, code) VALUES ('/induction-vs-ceramic-hob-whats-best-for-you/', '/buying-guide/which-is-better-induction-or-ceramic-cooker/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/jf_kv/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/jw-sanitary_kv/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kah-hoe-enterprise_sr/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kbo_jingjang_kv/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kbo_seminyih/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kbo-megastore-kucai-lama/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchenwise-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kucha-uptown_kv/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/living-portal_kv/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/ltl-global-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/mandi_kv/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/multi-skill-kitchen-design-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/mum-kitch-bandar-sunway/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/mum-kitch-bj_kv/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/nikko-kitchen-design-melaka/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/nikko-kitchen-design-muar/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/nova_sm/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/perfect-electrical-setia-alam/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/perfect-electrical-usj-taipan/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/py-lighting-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/sin-jin-da_nr/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/sk-bintulu_sm-2/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/sk-hardware-kuching/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/sk-miri_sm/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/standard-kitchen-sdn-bhd_sm/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/tahol-marketing_nr/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/tanradio-com-electrical-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/tanradio-com-kulai-1/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/tanradio-com-seri-alam/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/tanradio-com-tun-aminah/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/tanradio-johor-jaya/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/tht_kv/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/tr-bp-tanradio-com-batu-pahat-branch/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/union-motors_ecm/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/union-motors-electrical-supplies-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/urbanez-kd_kv/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/urbanez-klang_kv/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/vintage-bath-kitchen_sabah_store/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/vintage-bath-kitchen-tawau/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/viva-nueva-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/whatsapp-image-2024-07-03-at-12-14-57-pm/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/world-bath-kitchen-sdn-bhd/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/wpc_ec/', '/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/xammax/', '/', 301);

-- ────────────────────────────────────────────────────────────────────────────
-- WordPress CPT permalinks duplicating a product page (32)
-- ────────────────────────────────────────────────────────────────────────────
INSERT INTO redirect (from_path, to_path, code) VALUES ('/combine-oven-cate/combi-oven-va03/', '/built-in-combi-oven-va03/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/combine-oven-cate/combi-oven-va05/', '/built-in-combi-oven-va05/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/combine-oven-cate/magic-series-va06/', '/vatti-magic-series-combi-oven-va06/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/combine-oven-cate/vatti-built-in-air-fryer-oven-o7559/', '/vatti-built-in-air-fryer-oven-07559/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/combine-oven-cate/vatti-built-in-microwave-m626/', '/built-in-microwave-m626/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cooker-hob-category/3-burner-gas-hob-c830g/', '/vatti-3-burner-gas-hob-c830g/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cooker-hob-category/ai-hob-c835g/', '/vatti-ai-hob-c835g/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cooker-hob-category/ceramic-cooker-hob-er3601t/', '/ceramic-cooker-hob-er3601t/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cooker-hob-category/ceramic-cooker-hob-er5902t/', '/ceramic-cooker-hob-er5902t/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cooker-hob-category/cooker-hob-c821g/', '/professional-series-c821g/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cooker-hob-category/flexi-hob-c822g/', '/vatti-flexi-hob-c822g/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cooker-hob-category/flexi-hob-c823g/', '/vatti-flexi-hob-c823g/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cooker-hob-category/magic-series-c861g/', '/vatti-magic-series-cooker-hob-c861g/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cooker-hob-category/olympic-hob-m822g/', '/vatti-oylimpic-hob-m822g/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cooker-hob-category/professional-series-c720s/', '/professional-series-c720s/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/cooker-hob-category/vatti-flexi-hob-c836g/', '/vatti-flexi-hob-c836g/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/dishwasher-cate/vatti-dishwasher-dwbb7/', '/vatti-dishwasher-dwbb7/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/aetheris-series-v929/', '/vatti-aetheris-series-cooker-hood-v929/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/artemis-series-v931/', '/artemis-series-t-type-range-hood-v931/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/artemis-series-v999/', '/athena-series-lifting-type-range-hood-v999/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/athena-series-v993/', '/athena-series-lifting-type-range-hood-v993/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/cooker-hood-v917-carbon-grey/', '/vatti-cooker-hood-v917-carbon-grey/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/cooker-hood-v917-white/', '/vatti-cooker-hood-v917-white/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/magic-series-v919/', '/vatti-magic-series-cooker-hood-v919/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/range-hood-v997/', '/vatti-range-hood-v997/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/slim-series-type-v995/', '/slim-series-type-range-hood-v995/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/slim-series-type-v996/', '/vatti-slim-series-type-range-hood-v996/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/smart-oxygen-v998/', '/vatti-smart-oxygen-range-hood-v998/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/stellar-series-v960/', '/vatti-stellar-series-cooker-hood-v960/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/triple-intake-series-v937/', '/triple-intake-series-t-type-cooker-hood-v937/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/kitchen-hood-categor/vatti-stellar-series-cooker-hood-v960/', '/vatti-stellar-series-cooker-hood-v960/', 301);
INSERT INTO redirect (from_path, to_path, code) VALUES ('/water-purifier-cate/vatti-one-tap-water-purifier-wdhg01-v818wd/', '/vatti-one-tap-water-purifier-wdhg01-with-v818wd/', 301);
